name: Continuos Delivery
on:
  push:
    branches: ['master']
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando el Proyecto
        uses: actions/checkout@v4
      - name: Instalacion de Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Configurando Gradle
        uses: gradle/gradle-build-action@v2
      - name: Garantiza execute permission para el gradlew
        run: chmod +x ./gradlew
      - name: Compila el Proyecto build Proyect
        run: ./gradlew build
      - name: Log In al DockerHub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extrae la metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: estebanbeco27/gestion_inventarios
      - name: Construye y sube la imagen de docker
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          images: estebanbeco27/gestion_inventarios
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
