name: Continuos Delivery
on:
  push:
    branches: ['master']
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando el Proyecto
        uses: actions/checkout@v4
      - name: Instalacion de Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Configurando Gradle
        uses: gradle/gradle-build-action@v2
      - name: Garantiza execute permission para el gradlew
        run: chmod +x ./gradlew
      - name: Compila el Proyecto build Proyect
        run: ./gradlew build
      - name: Log In al DockerHub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: estebanbeco27/gestion_inventarios
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Construye y sube la imagen de docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}