name: Continuos Integration
on:
  pull_request:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando el Proyecto
        uses: actions/checkout@v4
      - name: Instalacion de Java
        uses: actions/set-upjava@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando Gradle
        uses: gradle/gradle-build-action@v2
      - name: Compila el Proyecto build Proyect
        run: ./gradlew build